version: '2'

services:
  route53-update:
    build: .
    environment:
      - LANG
      - OUTPUT
      - REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DOMAIN=example.com
      - HOSTED_ZONE_ID=*************
      - SLACKAPI=https://hooks.slack.com/services/*******************/************************
    container_name: route53-update

